<?php

namespace AppBundle\Repository;

/**
 * Book
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Book extends \Doctrine\ORM\EntityRepository
{
	public function findAllNotBooked()
{
    $query = $this->getEntityManager()
        ->createQuery(
            'SELECT b, bk FROM AppBundle:Book b
            JOIN b.booking bk
            WHERE bk.status <> :status'
        )->setParameter('status', 'zarezewowane');

    try {
        return $query->getResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
}
}
