<?php

namespace AppBundle\Repository;

/**
 * Booking
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Booking extends \Doctrine\ORM\EntityRepository
{
}
