<?php

namespace AppBundle\Repository;

/**
 * Book
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Book extends \Doctrine\ORM\EntityRepository
{
}
